
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/capability-app:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/capability-app:${SHORT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run','deploy','capability-app','--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/capability-app:${SHORT_SHA}','--region=${_REGION}','--platform=managed','--allow-unauthenticated']
substitutions:
  _REGION: europe-west1
  _REPO: app-images
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/capability-app:${SHORT_SHA}'
